### ISSUE TITLE
Display something more useful than whitespace when WDQS yields nothing

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#1646]
E.g. as in the second query at https://scholia.toolforge.org/location/Q211970 , nothing is displayed, not even the query or a "nothing found" message.

I think we had a ticket for that but cannot find it right now, and it came up in the context of reviewing https://github.com/WDscholia/scholia/pull/1577 , where I also have images.

**Comment by DanielFLopez** [comment]
@Daniel-Mietchen the problem with the query is that it is failing due to exceeding the response time, when it fails I can add a message but I don't know if this is the expected behavior, because you have to wait for the query to fail

<img width="837" alt="Screen Shot 2021-08-31 at 2 45 36 PM" src="https://user-images.githubusercontent.com/14321810/131566195-6745477b-515c-47bf-bc37-3cc0e5448c5d.png">

if I added it,  it would look something like this

<img width="1181" alt="Screen Shot 2021-08-31 at 2 46 28 PM" src="https://user-images.githubusercontent.com/14321810/131566304-050aee2a-1c1d-4709-8f29-216e0637c51f.png">

This would be to emphasize that it failed, which is not the same as "This query yielded no results."

**Comment by Daniel-Mietchen** [comment]
@DanielFLopez I agree that a distinction between a failed query and one that yielded no results is useful.

I would highlight that it timed out, make sure the query is accessible to the user and add a message inviting them to modify the query to be a bit less resource intensive.
