### ISSUE TITLE
RSS feed generators causes HTTP 500

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#243]
For 
https://tools.wmflabs.org/scholia/topic/Q24454422/latest-works/rss ,
I am currently getting
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by fnielsen** [comment]
There are still an issue with old authors, e.g., https://tools.wmflabs.org/scholia/author/Q859/latest-works/rss

**Comment by egonw** [comment]
It works for me now... @fnielsen, did you fix data and was that the problem? Or is it likely a time out?

If the latter, it's a code bug as the proper response code is "408 Request Timeout"...

**Comment by fnielsen** [comment]
I "hacked" it. It is not a proper fix. There are problems with authors such as Aristotle because of date conversion. I dont think RFC 2822 supports old dates. "year = 4*DIGIT / obs-year" - https://www.ietf.org/rfc/rfc2822.txt. Years between 1 and 999 could be represented as with prepadded zeros, but BC years are apparently not supported. I cannot see how it can be expressed in ISO 8601.

**Comment by egonw** [comment]
What is the state of this? Both queries work for me now.

**Comment by fnielsen** [comment]
I do get an empty result for https://tools.wmflabs.org/scholia/author/Q859/latest-works/rss

**Comment by Daniel-Mietchen** [comment]
Looks good to me now. @egonw @fnielsen Shall we close this?
