### ISSUE TITLE
Unable to get to Scholia this morning 

### ISSUE THREAD

**Issue by HelsKRW** [WDscholia/scholia#2538]
Hi, I'm getting a 504 timeout message on Scholia.  Is that something you're able to help with, or is it a wider toolforge issue?  
Thanks!
Best wishes
Helen 
![image](https://github.com/user-attachments/assets/bc846acc-e695-4590-9821-95acb6792ad0)

**Comment by fnielsen** [comment]
Yes, I did get that too. It must have been a Toolforge-wide issue as I even could not log into the Toolforge server. Looking at the Grafana logs it seems that it was from 12:00 to around 14:00 CEST and has since been normal. 

https://grafana.wmcloud.org/d/TJuKfnt4z/kubernetes-namespace?orgId=1&var-namespace=tool-scholia&var-cluster=prometheus-tools

I will take it that this was a temporary transient problem.
