### ISSUE TITLE
Security issues for zipp<3.19.1 and urllib3<1.26.19

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2562]
**Describe the bug**
Security issues for zipp<3.19.1 and urllib3<1.26.19

* https://www.cve.org/CVERecord?id=CVE-2024-5569
* https://www.cve.org/CVERecord?id=CVE-2024-37891

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Update the versions of zipp and urllib3 in requirements.txt to fix security issues CVE-2024-5569 and CVE-2024-37891.

I also created pull request: https://github.com/WDscholia/scholia/pull/2564


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
