### ISSUE TITLE
Provide way to link to individual panels in an aspect

### ISSUE THREAD

**Issue by Daniel-Mietchen** [WDscholia/scholia#348]
ideally in a persistent way

**Comment by nunogit** [comment]
In a GUI agnostic way, I would suggest using the fragment (#) part of the URL to identify a particular panel. Alternatively, create subaspect with a specific URI - https://tools.wmflabs.org/scholia/author/Q18618629/list-of-publications

**Comment by fnielsen** [comment]
The page fragment method is used, not widely nor consistent.

**Comment by Daniel-Mietchen** [comment]
I think either is fine for the moment, as long as we can make it more consistent.

In the long run, I would prefer the subaspect approach, e.g.
https://tools.wmflabs.org/scholia/author/Q18618629/list-of-publications
as above and then
https://tools.wmflabs.org/scholia/author/Q18618629/list-of-publications/missing
and
https://tools.wmflabs.org/scholia/authors/Q18618629,Q80/works-per-year 
and
https://tools.wmflabs.org/scholia/authors/Q18618629,Q80/works-per-year/missing .

This would require some priority order, e.g. /missing should always come at the end.

**Comment by carlinmack** [comment]
Using the fragment is preferable as it can be done natively in the browser. Simply, a link can be used (that can look like a button) that targets the id you want to jump to, such as [Labels in the sidebar](#labels-select-menu) (test by clicking that link)

Otherwise to maintain that URL structure, flask+jquery can be used. @Daniel-Mietchen, which would you prefer?

**Comment by carlinmack** [comment]
Additionally, having a sub-aspect approach rather than fragment approach will create duplicate pages in Google search results which may affect SEO. I don't think that this can be avoided with the `canonical` head tag as I think this might cause a redirect to the base page and therefore not link to a panel.

**Comment by Daniel-Mietchen** [comment]
I think going for fragments makes the most sense here.
